version: '3'

services:

  server:
    network_mode: host
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
      - partner-service

  partner-service:
    network_mode: host
    build:
      context: ./partner-service
      dockerfile: Dockerfile
          
  db:
    image: postgres:13.3
    container_name: db
    network_mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=data
